<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product = [
            [
                'name' => 'CCLF 64 D, BROWN WALNUT',
                'category_id' => 1,
                'price' => 380000,
                'stock' => 3,
                'thumbnail' => 'rak penyimpanan, Calculus Frame Double, Double Row',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'PRO OAK - WHITE MARBLE',
                'category_id' => 1,
                'price' => 3300000,
                'stock' => 80,
                'thumbnail' => 'TETRA SB4+3 NEO BUFET / KABINET / MEJA TV / RAK TV',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 1,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 1,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 1,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 2,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 2,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 2,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 2,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 2 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 2 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 2,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 2 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 3,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 3,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 3,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 3,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 3 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 3 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 3,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 3 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 4,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 4,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 4,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 4,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 4 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 4 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 4,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 4 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 5,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 5,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 5,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 5,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 5 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 5 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 5,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 5 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 6,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 6,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 6,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 6,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 6 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 6 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 6,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 6 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 7,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 7,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 7,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 7,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 7,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 8,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 8,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 8,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 8,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 8,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 9,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 9,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 9,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 9,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 9,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 10,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 10,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 10,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 10,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 10,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 11,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 11,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 11,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 11,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 11,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 12,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 12,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 12,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 12,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 12,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 13,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 13,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 13,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 13,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 13,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 14,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 14,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 14,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 14,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 14,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 15,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 15,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 15,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 15,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 15,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 16,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 16,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 16,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 16,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 16,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 17,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 17,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 17,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 17,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 17,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],

            [
                'name' => 'kayu batangan',
                'category_id' => 18,
                'price' => 70000,
                'stock' => 100,
                'thumbnail' => 'product1 ini keren',
                'description' => 'product1 ini hebat dan keren',
            ],
            [
                'name' => 'lemari baju',
                'category_id' => 18,
                'price' => 80000,
                'stock' => 80,
                'thumbnail' => 'product2 ini keren',
                'description' => 'product2 ini hebat dan keren',
            ],
            [
                'name' => 'kasur',
                'category_id' => 18,
                'price' => 90000,
                'stock' => 20,
                'thumbnail' => 'product3 ini keren',
                'description' => 'product3 ini hebat dan keren',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 18,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],
            [
                'name' => 'meja kaca',
                'category_id' => 18,
                'price' => 5000000,
                'stock' => 90,
                'thumbnail' => 'kaca tebal 1 mm, kuat tahan banting dll, ga percaya coba aja sana',
                'description' => '<ol><li>cara pemasangan ada petunjuk didalam kardus</li><li>garansi 1 tahun</li><li>jika order sudah di kurir maka bukan tanggung jawab kami</li></ol>',
            ],


        ];

        DB::table('products')->insert($product);
    }
}
