INSERT INTO jokian_ecommerce.products (category_id,name,stock,price,thumbnail,description,created_at,updated_at) VALUES
	 (1,'CCLF 64 D, BROWN WALNUT',3.0,380000.0,'CALCULUS RANGKA KABINET MODULAR','<ul><li>Calculus Frame Double, Double Row</li><li>Rangka untuk kabinet / rak penyimpanan</li><li>Rangka utama, langkah awal dalam menyusun kombinasi Calculus&nbsp;</li><li>Dapat ditempatkan dilantai atau ditempel pada dinding&nbsp;</li><li>Tambahkan kaki, rak tambahan, pintu dan laci sesuai kebutuhan. Dijual terpisah</li></ul>',NULL,'2023-10-28 14:56:50'),
	 (1,'PRO OAK - WHITE MARBLE',80.0,3300000.0,'TETRA SB4+3 NEO BUFET / KABINET / MEJA TV / RAK TV','<ul><li>Metal handle&nbsp;</li><li>Memiliki banyak ruang penyimpanan&nbsp;</li><li>Bentuk tebal pada bagian atas dan samping memberikan kesan kuat dan kokoh&nbsp;</li><li>Kaki tinggi memberikan kesan ringan dan luas &amp; memudahkan anda untuk membersihkan kolong.&nbsp;</li><li>Tinggi rak dapat diatur sesuai kebutuhan</li></ul>',NULL,'2023-10-28 14:58:56'),
	 (1,'DARYA SB120  WHITE SM - PRO OAK',4.0,1360000.0,'DARYA SB120 BUFET / KABINET / MEJA TV / RAK TV','<ul><li>Bagian rak dapat diatur sesuai dengan kebutuhan (adjustable)&nbsp;</li><li>Material tebal, kuat dan kokoh&nbsp;</li><li>Kaki tinggi memberikan kesan ringan dan luas &amp; memudahkan untuk membersihkan kolong</li></ul>',NULL,'2023-10-28 15:02:50'),
	 (2,'VOBD 160  PRO OAK',80.0,2130000.0,'VOLTA DIVAN / TEMPAT TIDUR DOUBLE','<ul><li>Desain simple dan minimalist&nbsp;</li><li>Alas tempat tidur dirancang kokoh untuk menopang matras&nbsp;</li><li>Kaki dipan tebal dan kuat</li></ul>',NULL,'2023-10-28 15:06:04'),
	 (3,'CLAVA N120  PRO OAK - GRANITE',100.0,2228000.0,'CLAVA N120 RAK DAPUR / LEMARI DAPUR','<ul><li>Tempat penyimpanan besar dengan banyak pintu dan laci&nbsp;</li><li>Ukuran memanjang keatas, tidak membutuhkan banyak space</li></ul>',NULL,'2023-10-28 15:11:55'),
	 (3,'OKLBU 2X3  BROWN WALNUT - WHITE MFC',80.0,2060000.0,'OKLAVA RAK DAPUR / BUFET DAPUR','<ul><li>Material alas meja menggunakan bahan berlapis Melamine, tahan air dan api&nbsp;</li><li>Alas meja tidak di design untuk sink atau kompor tanam&nbsp;</li><li>Solusi penyimpanan diseluruh area rumah seperti dapur, ruang cuci, garasi, dsb&nbsp;</li><li>Untuk dikombinasikan dengan seri Oklava lainnya</li></ul>',NULL,'2023-10-28 15:17:00'),
	 (3,'OKLBU 3  BROWN WALNUT - WHITE MFC',20.0,1750000.0,'OKLAVA RAK DAPUR / BUFET DAPUR','<ul><li>Material alas meja menggunakan bahan berlapis Melamine, tahan air dan api&nbsp;</li><li>Alas meja tidak di design untuk sink atau kompor tanam&nbsp;</li><li>Solusi penyimpanan diseluruh area rumah seperti dapur, ruang cuci, garasi, dsb&nbsp;</li><li>Untuk dikombinasikan dengan seri Oklava lainnya</li></ul>',NULL,'2023-10-28 15:15:58'),
	 (3,'OKLBU 98C  BROWN WALNUT - WHITE MFC',90.0,960000.0,'OKLAVA RAK DAPUR SUDUT / BUFET DAPUR SUDUT','<ul><li>Material alas meja menggunakan bahan berlapis Melamine, tahan air dan api&nbsp;</li><li>Alas meja tidak di design untuk sink atau kompor tanam&nbsp;</li><li>Solusi penyimpanan diseluruh area rumah seperti dapur, ruang cuci, garasi, dsb&nbsp;</li><li>Untuk dikombinasikan dengan seri Oklava lainnya</li></ul>',NULL,'2023-10-28 15:14:38'),
	 (3,'OKLBU 98C GL  WHITE GLOSSY - WHITE MFC',90.0,1040000.0,'OKLAVA RAK DAPUR SUDUT / BUFET DAPUR SUDUT','<ul><li>Material alas meja menggunakan bahan berlapis Melamine, tahan air dan api&nbsp;</li><li>Alas meja tidak di design untuk sink atau kompor tanam&nbsp;</li><li>Solusi penyimpanan diseluruh area rumah seperti dapur, ruang cuci, garasi, dsb&nbsp;</li><li>Untuk dikombinasikan dengan seri Oklava lainnya</li></ul>',NULL,'2023-10-28 15:13:34'),
	 (4,'PADME EC PRO  BLACK',100.0,1190000.0,'PADME EC PRO KURSI KERJA','<ul><li>Sandaran menggunakan bahan mesh, membantu sirkulasi udara pada bagian punggung agar tidak panas&nbsp;</li><li>Desain sandaran mengikuti bentuk pinggang&nbsp;</li><li>Dapat berputar 360o&nbsp;</li><li>Kaki roda berputar mulus&nbsp;</li><li>Tinggi kursi bisa disesuaikan</li></ul>',NULL,'2023-10-28 15:21:14');
INSERT INTO jokian_ecommerce.products (category_id,name,stock,price,thumbnail,description,created_at,updated_at) VALUES
	 (4,'CITRI  BLACK',80.0,750000.0,'CITRI KURSI KERJA / KURSI STAFF','<ul><li>Sandaran menggunakan bahan mesh, membantu sirkulasi udara pada bagian punggung agar tidak panas&nbsp;</li><li>Desain sandaran mengikuti bentuk pinggang&nbsp;</li><li>Dapat berputar 360o&nbsp;</li><li>Kaki roda berputar mulus&nbsp;</li><li>Tinggi kursi bisa disesuaikan</li></ul>',NULL,'2023-10-28 15:22:23'),
	 (4,'ELOK DC',20.0,530000.0,'ELOK DC KURSI MAKAN / KURSI CAFE','<ul><li>Hanya bisa dipakai di dalam ruangan&nbsp;</li><li>Dapat menjadi kering dan menyusut jika berdekatan dengan radiator atau sumber panas lainya&nbsp;</li><li>Setiap kursi ini unik karena dibuat dengan tangan&nbsp;</li><li>Dibuat dari bahan alami, ringan, kuat, dan tahan lama</li></ul>',NULL,'2023-10-28 15:23:15'),
	 (4,'DORME EC PRO  BLACK',90.0,950000.0,'DORME EC PRO KURSI KERJA','<ul><li>Sandaran menggunakan bahan mesh, membantu sirkulasi udara pada bagian punggung agar tidak panas&nbsp;</li><li>Desain sandaran mengikuti bentuk pinggang&nbsp;</li><li>Dapat berputar 360o&nbsp;</li><li>Kaki roda berputar mulus&nbsp;</li><li>Tinggi kursi bisa disesuaikan</li></ul>',NULL,'2023-10-28 15:24:20'),
	 (4,'FORLISA  WHITE',90.0,240000.0,'FORLISA KURSI MAKAN / KURSI CAFE','<ul><li>Dapat dilipat dan digantung&nbsp;</li><li>Kursi ini ringan dan sangat kuat karena terbuat dari bahan besi dan plastik</li></ul>',NULL,'2023-10-28 15:25:01'),
	 (5,'CLOUD ET2 NEO  BROWN WALNUT',100.0,580000.0,'CLOUD ET2 NEO LEMARI LACI / MEJA SAMPING / NAKAS / PEDESTAL','<ul><li>Laci untuk menyimpanan barang&nbsp;</li><li>Material tebal dan kokoh&nbsp;</li><li>Terdapat kaki memudahkan membersihkan kolong</li></ul>',NULL,'2023-10-28 15:27:17'),
	 (5,'CLOUD CD4 NEO  PRO OAK',80.0,1400000.0,'CLOUD CD4 NEO LEMARI LACI','<ul><li>Laci penyimpanan serbaguna&nbsp;</li><li>Handle-free&nbsp;</li><li>Rel laci yang rigid dan melaju mulus saat ditarik&nbsp;</li><li>Terdapat kaki memudahkan membersihkan kolong</li></ul>',NULL,'2023-10-28 15:28:06'),
	 (6,'TXWD 160 SSL  BROWN WALNUT',100.0,4499000.0,'TEXAS LEMARI PAKAIAN PINTU SLIDING','<ul><li>Kaca besar agar anda lebih nyaman pada saat berkaca&nbsp;</li><li>Metal handle&nbsp;</li><li>Dilengkapi dengan laci sebagai tempat penyimpanan tersembunyi dan juga bebas debu&nbsp;</li><li>Rak dapat disesuaikan dengan penyimpanan yang anda butuhkan&nbsp;</li><li>Jumlah rak baju sangat banyak&nbsp;</li><li>Ketebalan papan 15 mm&nbsp;</li><li>Material tebal, kokoh dan kuat&nbsp;</li><li>Ukuran lemari cukup tinggi dan besar&nbsp;</li><li>Terdapat 2 model pintu yaitu pintu swing dan sliding</li></ul>',NULL,'2023-10-28 15:32:45'),
	 (6,'VGSWD 2FN  PRO OAK',80.0,3220000.0,'VEGAS LEMARI PAKAIAN 2 PINTU','<ul><li>Cermin besar untuk kenyamanan berdandan &nbsp;</li><li>Dilengkapi dengan laci sebagai tempat penyimpanan tersembunyi dan juga bebas debu&nbsp;</li><li>Rak dapat disesuaikan dengan penyimpanan yang anda butuhkan &nbsp;</li><li>Material tebal, kokoh dan kuat&nbsp;</li><li>Ukuran lemari cukup tinggi dan besar</li></ul>',NULL,'2023-10-28 15:33:54'),
	 (6,'VGSWD 2FN  BROWN WALNUT',20.0,3220000.0,'VEGAS LEMARI PAKAIAN 2 PINTU','<ul><li>Cermin besar untuk kenyamanan berdandan&nbsp;</li><li>Metal handle&nbsp;</li><li>Dilengkapi dengan laci sebagai tempat penyimpanan tersembunyi dan juga bebas debu&nbsp;</li><li>Rak dapat disesuaikan dengan penyimpanan yang anda butuhkan&nbsp;</li><li>Jumlah rak baju sangat banyak&nbsp;</li><li>Ketebalan papan 15 mm&nbsp;</li><li>Material tebal, kokoh dan kuat Ukuran lemari cukup tinggi dan besar</li></ul>',NULL,'2023-10-28 15:35:01');
